name: Test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.nodeversion }}"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        nodeversion: ['12.x', '13.x', '14.x', '15.x']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v"${{ matrix.nodeversion }}""
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: test
        env:
          YARN_GPG: no 
        run: yarn test
